# Generated by Django 2.0 on 2019-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_tlp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
