# Generated by Django 2.0 on 2019-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190819_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no_tlp',
            field=models.CharField(max_length=100),
        ),
    ]
