# Generated by Django 3.1 on 2020-11-15 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=300)),
                ('phone_resto', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('resto_street_address', models.CharField(max_length=300)),
                ('resto_zip_code', models.CharField(max_length=25)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL)),
                ('resto_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_in_city', to='administrative.city')),
                ('resto_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_in_district', to='administrative.district')),
                ('resto_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_in_province', to='administrative.province')),
                ('resto_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_in_village', to='administrative.villages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_table', models.PositiveIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_tables', to='resto.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
